spring:
  datasource:
    url: jdbc:mysql://localhost/smartnews_db?useSSL=false
    username: dev
    password: dev2020?
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: false
  thymeleaf:
    cache: false